'use client';

import React, { useState } from 'react';
import CardTemplate from './CardTemplate';

// --- DATA SOURCE ---
const userData = {
  id: 5,
  created_at: '2025-06-17T13:14:47.242579+00:00',
  name: 'Ananda Sayanan s',
  position: 'Anlyt Media',
  org: 'Anlyt Media',
  email: 'hello@anlytmedia.in',
  phones: ['+917092828370', '+918428524861'],
  address: '18/16/3, Elavuvilai Jn, Marthandam, TN 629191, India',
  address_link: null,
  logo: '/app-bar-logo.svg', // Using icon as placeholder in UI
  bgLogo: 'bg-slate-500',
  bgColor: 'from-slate-600 to-slate-800 card-bg',
  textColor: 'text-white',
  cardColor:
    'bg-white/10 backdrop-blur-md border border-white/20 shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]',
  buttonColor: 'bg-slate-500',
  enableContactButton: true,
  enableSocialLinks: true,
  socialLinks: {
    instagram: 'https://www.instagram.com/anlytmedia',
    facebook: 'https://www.facebook.com/anlytmedia',
    linkedin: 'https://www.linkedin.com/company/anlytmedia',
    twitter: 'https://www.twitter.com/anlytmedia',
  },
  endpoint: 'sayanan',
};

interface ContactRowProps {
  icon: React.ComponentType<{ size?: number; className?: string }>;
  text: string;
  className?: string;
}

const ContactRow: React.FC<ContactRowProps> = ({
  icon: Icon,
  text,
  className = '',
}) => (
  <div className={`flex items-center gap-2 ${className}`}>
    <Icon size={14} className='shrink-0' />
    <span className='text-xs truncate'>{text}</span>
  </div>
);

// --- TEMPLATE RENDERER ---

// --- MAIN APP COMPONENT ---

const CardGallery = () => {
  const [filter, setFilter] = useState('all');

  const categories = [
    { id: 'all', name: 'All Templates' },
    { id: 'corporate', name: 'Corporate' },
    { id: 'creative', name: 'Creative' },
    { id: 'minimal', name: 'Minimal' },
  ];

  return (
    <div className='min-h-screen bg-slate-100 p-8 font-sans'>
      <div className='max-w-7xl mx-auto'>
        {/* Header */}
        <div className='mb-12 text-center'>
          <h1 className='text-4xl font-bold text-slate-800 mb-4'>
            Anlyt Media
          </h1>
          <p className='text-slate-500 max-w-2xl mx-auto'>
            Viewing 25 unique templates generated by Anlyt Media
          </p>
        </div>

        {/* Grid */}
        <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-8'>
          {Array.from({ length: 25 }, (_, i) => i + 1).map((variant) => (
            <div key={variant} className='flex flex-col gap-2'>
              <div className='flex justify-between items-end px-1'>
                <span className='text-xs font-bold text-slate-400 uppercase tracking-wider'>
                  Template {variant}
                </span>
              </div>
              <div className='shadow-lg rounded-xl'>
                <CardTemplate variant={variant} data={userData} />
              </div>
            </div>
          ))}
        </div>

        <div className='mt-16 text-center text-slate-400 text-sm'>
          Generated for Anlyt Media • 2025
        </div>
      </div>
    </div>
  );
};

export default CardGallery;
